" VIM CONFIG FILE

" Windows path: C:\Program Files (x86)\Vim

" Vim is based on Vi. Setting `nocompatible` switches from the default Vi-compatibility mode and enables useful Vim functionality. This
" configuration option turns out not to be necessary for the file named '~/.vimrc', because Vim automatically enters nocompatible mode if that file
set nocompatible

" Turn on syntax highlighting.
syntax on

" Disable the default Vim startup message.
set shortmess+=I

" Show line numbers.
set number

" Always show the status line at the bottom, even if you only have one window open.
set laststatus=2

" Backspace over anything.
set backspace=indent,eol,start

" By default, Vim doesn't let you hide a buffer (i.e. have a buffer that isn't
" shown in any window) that has unsaved changes. This is to prevent you from "
" forgetting about unsaved changes and then quitting e.g. via `:qa!`. We find
" hidden buffers helpful enough to disable this protection. See `:help hidden`
" for more information on this.
set hidden

" Makes search case-insensitive when all characters in the string
" being searched are lowercase. However, the search becomes case-sensitive if it contains any capital letters. This makes searching more convenient.
set ignorecase
set smartcase

" Enable searching as you type, rather than waiting till you press enter.
set incsearch

" Unbind some useless/annoying default key bindings.
nmap Q <Nop> " 'Q' in normal mode enters Ex mode. You almost never want this.

" Disable audible bell because it's annoying.
set noerrorbells visualbell t_vb=

" Enable mouse support. You should avoid relying on this too much, but it can sometimes be convenient.
set mouse+=a
